"""First migrate

Revision ID: 768fedb9eba0
Revises: 
Create Date: 2022-12-26 22:30:02.292328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768fedb9eba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departament_types',
    sa.Column('departament_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('departament_type_id', name=op.f('pk_departament_types'))
    )
    op.create_table('placements',
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('placement_id', name=op.f('pk_placements'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('room_height_type',
    sa.Column('room_height_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('room_height_type_id', name=op.f('pk_room_height_type'))
    )
    op.create_table('room_type',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('room_type_id', name=op.f('pk_room_type'))
    )
    op.create_table('departaments',
    sa.Column('departament_id', sa.Integer(), nullable=False),
    sa.Column('departament_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departament_type_id'], ['departament_types.departament_type_id'], name=op.f('fk_departaments_departament_type_id_departament_types')),
    sa.PrimaryKeyConstraint('departament_id', name=op.f('pk_departaments'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('departament_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departament_id'], ['departaments.departament_id'], name=op.f('fk_buildings_departament_id_departaments')),
    sa.PrimaryKeyConstraint('building_id', name=op.f('pk_buildings'))
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('room_height_type_id', sa.Integer(), nullable=True),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], name=op.f('fk_rooms_building_id_buildings')),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.placement_id'], name=op.f('fk_rooms_placement_id_placements')),
    sa.ForeignKeyConstraint(['room_height_type_id'], ['room_height_type.room_height_type_id'], name=op.f('fk_rooms_room_height_type_id_room_height_type')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.room_type_id'], name=op.f('fk_rooms_room_type_id_room_type')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_rooms'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('buildings')
    op.drop_table('users')
    op.drop_table('departaments')
    op.drop_table('room_type')
    op.drop_table('room_height_type')
    op.drop_table('roles')
    op.drop_table('placements')
    op.drop_table('departament_types')
    # ### end Alembic commands ###
